#!/bin/bash

ROOT=false
STOP=false
ARGS=()

for arg in "$@"; do
    if [ "$arg" = "--root" ]; then
        ROOT=true
    elif [ "$arg" = "--stop" ]; then
        STOP=true
    else
        ARGS+=("$arg")
    fi
done

if [ "$STOP" = true ]; then
    docker compose -f docker-compose-dev.yml down
    
elif [ "$ROOT" = true ]; then
    docker exec -it ops-dev-app-1 "${ARGS[@]}"
    
else
    docker exec -it --user "$(id -u):$(id -g)" ops-dev-app-1 "${ARGS[@]}"
fi