name: ops

services:

    redis:
        image: redis:7.2-alpine
        container_name: redis
        restart: unless-stopped
        command: >
            redis-server
            --appendonly yes
            --appendfsync everysec
            --maxmemory 512mb
            --maxmemory-policy allkeys-lru
            --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis-data:/data
        networks:
            - internal-net
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

    db:
        image: postgres:17
        restart: always
        volumes:
            - pg-data:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - "127.0.0.1:5433:5432"
        environment:
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB_DATABASE}"
        networks:
            - public-net
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
            interval: 10s
            timeout: 10s
            retries: 10

    app:
        image: elyerr/oauth2-passport-server
        restart: always
        ports:
            - "8001:80"
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - .env:/root/.env
            - app-secrets:/var/www/secrets
            - files:/var/www/storage/app
            - sitemaps:/var/www/public/sitemaps
            - logs:/var/www/storage/logs
            - third-party:/var/www/third-party
            - third-party-public:/var/www/public/third-party
            - editable:/resources/views/layouts
        #    - ${SSH_DIR}:/var/www/.ssh:ro
        #    - ${GIT_CONFIG}:/var/www/.gitconfig:ro
        command: sh -c "/usr/local/bin/entrypoint.sh"
        networks:
           - public-net

volumes:
    pg-data:
    app-secrets:
    files:
    sitemaps:
    logs:
    third-party:
    third-party-public:
    editable:

networks:
    public-net:
        driver: bridge
