#!/bin/bash
ROOT=false
STOP=false
ARGS=()

for arg in "$@"; do
    if [ "$arg" = "--root" ]; then
        ROOT=true
    elif [ "$arg" = "--stop" ]; then
        STOP=true
    else
        ARGS+=("$arg")
    fi
done

if [ "$STOP" = true ]; then
    docker compose -f docker-compose-prod.yml down

elif [ "$ROOT" = true ]; then
    docker exec -it ops-app-1 "${ARGS[@]}"

else
    docker exec -it --user "www-data:www-data" ops-app-1 "${ARGS[@]}"
fi